title: "William Hartono"
email: "wholidipro@gmail.com"
description: "Digital Transformation | AI Audit | SAP S/4 HANA | 24+ Years | 29 Projects | 55 Countries"
baseurl: ""
url: "https://wholidi.github.io"
github_username: "wholidi"
linkedin_username: "whartono"
# theme: jekyll-theme-minimal

collections:
  pages:
    output: true
    permalink: /:name
  skills:
    output: true
    permalink: /skills/:name/

enable_project_categories: true
